import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import QuickContact from './components/QuickContact';


export const metadata = {
  title: 'Car Hire Mumbai',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <QuickContact /> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
