import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/index";
import BottomNav from "./components/BottomNav";

export const metadata = {
  title: "CarHireMumbai | Book Now",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <div className="md:hidden block">
          <BottomNav />
        </div>
        <Footer />
      </body>
    </html>
  );
}
